#!/usr/bin/env python3
import os
from pathlib import Path

devenv = Path(__file__).parent.resolve()

symlinks = [
    ("~/.dircolors", "dotfiles/dircolors/dircolors"),
    ("~/.emacs", "emacs-config/emacs.el"),
    ("~/.gitconfig", "dotfiles/git/gitconfig"),
    ("~/.pdbrc.py", "dotfiles/pdbrc.py"),
    ("~/.tmux.conf", "dotfiles/tmux/tmux.conf"),
    ("~/.zshrc", "shell-config/init.sh"),
    ("~/.ohmyzsh", "ohmyzsh"),
    ("~/bin", "bin"),
]

for (source, _target) in symlinks:
    target = devenv / _target
    os.system(f"ln -sf {target} {source}")
